export const SET_GOODS_LIST = "SET_GOODS_LIST";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const CHANGE_BASKET_AMOUNT = "CHANGE_BASKET_AMOUNT";
export const TOGGLE_FAVOURITE = "TOGGLE_FAVOURITE";
